import { Outfit, Roboto } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Synoize | Learn Next App",
    template: "%s | Learn Next App"
  },
  description: "Generated by create next app",
  authors: [{ name: "synoize" }, { name: "shivam singh", url: "learn-next-app.io" }],
  keywords: ["nextjs", "reactjs"],
  icons: {
    icon: "/vercel.svg"
  },
  metadataBase: new URL("https://learn-next-app.io"),
  openGraph: {
    title: "Synoize | Learn Next App",
    description: "Generated by create next app",
    url: "https://learn-next-app.io",
    siteName: "Learn Next App",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 640,
        alt: "learn next app",
      }
    ],
    type: "website"
  },
  twitter: {
    card: "sumarry_large_card",
    title: "Synoize | Learn Next App",
    description: "Generated by create next app",
    creator: "@synoize",
    images: ["/og-image.png"],
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${outfit.variable}`}
      >
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
