import React from 'react'

export const metadata = {
  title: "About Page",
  description: "About page Generated by create next app",
};

export default function Aboutlayout({ children }) {
    return (
        <div>
            {children}
        </div>
    )
}
