import { Outfit } from "next/font/google";
import "../globals.css";
import Navigation from "@/components/Navigation";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Learn Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        <Navigation />
        <div className='max-w-7xl mx-auto p-8'>
          {children}
        </div>
      </body>
    </html>
  );
}
